### ISSUE TITLE
Scope view

### ISSUE THREAD

**Issue by dynfer** [fiztech-code/BeanMPX#10]
Hello, im currently porting Your code to STM32, im having some issues with the timer synchronization on RX part, TX works flawlessly.
Would You happen to have some scope screen's when the Compare ISR receive() is called?

**Comment by fiztech-code** [comment]
Hi there, i do not have a scope view. what i encountered with RX on BeamMPX is there is additional time allocated for rise and fall of signal. for example, 1bit is 100ms, rise and fall time is 5ms each, total is 110ms. however if there are consecutive 5bits then total time would be 510ms. The way i tackled this by attaching an ISR to the RX pin and whenever there is rise or fall edge detected i reset timer counter to middle of square wave.
