### ISSUE TITLE
BeanMPX on Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by SMP-DarkSonic** [fiztech-code/BeanMPX#3]
Hi,

i wanted to run your BeanMPX on a Nano 33 BLE with a M4. After adding the Library to my project I get several errors. 
Do you plan to adapt the Library to be compatible with the more powerfull Nano 33 or other Boards like the Adafruit M0 Boards?

**Comment by fiztech-code** [comment]
no plans to port this project to other microcontrollers at this time
