### ISSUE TITLE
Square wave signal on TX signal

### ISSUE THREAD

**Issue by SMP-DarkSonic** [fiztech-code/BeanMPX#4]
Hi,

tested your new version of the library today. 
I have a square wave signal on the TX line and in between the send data. Have tested it on different Nano but every time with the same result.
Switched back to your old version and everything worked fine.

Rgerads

**Comment by fiztech-code** [comment]
i modified the circuit to use invert logic for TX
in future i will add feature to use either none-invert or invert logic to the TX pin

also now you have to specify which pins to use for RX, TX pins, i tested with PortD and PortB 

there are a few array out of bound fixes in the new code, so i would try to use it
