### ISSUE TITLE
Attiny Support

### ISSUE THREAD

**Issue by hyperlite2** [fiztech-code/BeanMPX#5]
Hi and thank you for your library. It is great!

I want to port it over to work on an Attiny85, but I can' seem to get it to work. There must be something over my head. I believe it has to do with the timer setup. I have tried to set the library to use Timer1 on the Attiny85, but have not been successful. I do not need serial com. Would you be willing to help me figure out what I am missing? I am willing to compensate for your time.

**Comment by fiztech-code** [comment]
Hi There
porting this library to attiny85 is possible but it will require considerable amount of effort
if you are looking to create a compact project why not go with atmega328p-au ( tqfp-32 ), its inexpensive and widely available

or perhaps atmega328p-mu ( mlf-32 ), which is a bit more rare
