### ISSUE TITLE
How to actually wire into a Toyota/Lexus vehicle

### ISSUE THREAD

**Issue by kerta1n** [fiztech-code/BeanMPX#7]
Hi fiztech,
What connection/wire do you tap into to get INTO the Bean bus? I have a 2004 Prius, have been trying to figure out ways to get rid of the ugly-looking MFD WITHOUT losing A/C control, and can't seem to find anything in the docs about how to actually connect to the car. Is it just through the OBD port? Maybe I'm missing something.
I know that in your demo you used the gauge cluster, but I'm trying to figure out a non-destructive way, as the Gen 2 Prius does not have an analog cluster of any kind

**Comment by fiztech-code** [comment]
sorry i dont know how to interface with bean bus on a 2004 prius

**Comment by kerta1n** [comment]
@fiztech-code I found this. http://static.hybrids.ru/files/OfficialToyotaInfo/RepairInformation/RepairManual/MP%20-%20Multiplex%20Communication.pdf
Seems to be for Priuses older than the 2004, but still Gen 2 (not important to you). Say I ended up T-tapping into one of these wires. How would I go about sending data to the ECU's?
