### ISSUE TITLE
Explanation of the timing strategy

### ISSUE THREAD

**Issue by Zephurah** [fiztech-code/BeanMPX#8]
Hello, I would like to know how the various timing functions operate in more detail than what I can figure out by looking at the code: 

Specifically when pins are read and how that correlates to the OCR1A and OCR1B registers. I am having a hard time understanding why the TCNT1 register is being set to the middle value once the receive interrupt is triggered, and how the code determines transmit timing with those values.

Thanks!

**Comment by fiztech-code** [comment]
Sorry for late response
the square wave is not exact.

For example, is 1 bit is 100ms, 5 bits will be less 450ms

Because BEAN is really long frame, sampling will fall behind. 

Therefore whenever there is a change of state the timer counter is reset to 1/2 length of 1bit
