### ISSUE TITLE
Can read data on one bus but not the other. 

### ISSUE THREAD

**Issue by KazanNinja** [fiztech-code/BeanMPX#9]
I'm working with a 2001 Toyota Celica cluster, which has two MPX buses, one to/from the engine ECU and one to/from the body ECU. I have used BeanMPX to successfully receive and transmit messages on the engine ECU bus (battery light, oil pressure light, and coolant temp), but I am unable to read anything off of the body ECU bus, however (I think) I can transmit messages. I have a body ECU here to confirm that the body functions (seatbelt warning, door open warning, and fuel level) are in working order, I just cannot see the messages that are transmitted from the body ECU. 

As far as I can tell, my circuitry matches your diagrams as I am able to do stuff with the engine ECU bus. Not sure if I'm just missing something though, I'm very new to this BEAN stuff. Thanks!

Toyota's MPX circuit here, MPX+/- on the ECU side are shorted together in the cluster and are not continuous with the body ECU side. 
![download](https://github.com/fiztech-code/BeanMPX/assets/13895569/80cfc305-0bdb-4115-ae92-4f8246ab7ad6)

**Comment by fiztech-code** [comment]
I cannot speak on the specifics of your setup, however as you are able to communicate with ecu and/or combination meter your circuit is correct. All i can recommend is isolate the body module and try to communicate with it directly.

You may be able to use a vag-com device as a transiver 

![f136a8ds-960](https://github.com/fiztech-code/BeanMPX/assets/66762914/9a67acd4-71e0-4aa8-a7e0-e058f4805676)
